//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoshJsonWebToken.Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AlgorithmStrings
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AlgorithmStrings()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PoshJsonWebToken.Resources.AlgorithmStrings", typeof(AlgorithmStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Certificate parameter requires any one of &apos;{0}&apos; JWE algorithms..
        /// </summary>
        internal static string CertificateRequiredJweAlgorithms
        {
            get
            {
                return ResourceManager.GetString("CertificateRequiredJweAlgorithms", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Certificate parameter requires any one of &apos;{0}&apos; JWS algorithms..
        /// </summary>
        internal static string CertificateRequiredJwsAlgorithms
        {
            get
            {
                return ResourceManager.GetString("CertificateRequiredJwsAlgorithms", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Compression parameter requires any one of &apos;{0}&apos; JWE encryptions..
        /// </summary>
        internal static string CompressionRequiresJweEncryption
        {
            get
            {
                return ResourceManager.GetString("CompressionRequiresJweEncryption", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Algorithm parameter requires any one of &apos;{0}&apos; algorithms..
        /// </summary>
        internal static string InvalidAlgorithm
        {
            get
            {
                return ResourceManager.GetString("InvalidAlgorithm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Encryption parameter requires any one of &apos;{0}&apos; JWE encryptions..
        /// </summary>
        internal static string InvalidJweEncryption
        {
            get
            {
                return ResourceManager.GetString("InvalidJweEncryption", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Encryption parameter requires any one of &apos;{0}&apos; JWE algorithms..
        /// </summary>
        internal static string JweEncryptionRequiredWithJweAlgorithm
        {
            get
            {
                return ResourceManager.GetString("JweEncryptionRequiredWithJweAlgorithm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The JWS algorithm &apos;{0}&apos; requires a key using -SecretKey or -Certificate parameters..
        /// </summary>
        internal static string JwsAlgorithmRequiresKey
        {
            get
            {
                return ResourceManager.GetString("JwsAlgorithmRequiresKey", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Using NONE (unprotected) plain text JWS algorithm without integrity protection..
        /// </summary>
        internal static string NoneJwsAlgorithmWarning
        {
            get
            {
                return ResourceManager.GetString("NoneJwsAlgorithmWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Secret parameter requires any one of &apos;{0}&apos; JWE algorithms..
        /// </summary>
        internal static string SecretRequiredJweAlgorithms
        {
            get
            {
                return ResourceManager.GetString("SecretRequiredJweAlgorithms", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Secret parameter requires any one of &apos;{0}&apos; JWS algorithms..
        /// </summary>
        internal static string SecretRequiredJwsAlgorithms
        {
            get
            {
                return ResourceManager.GetString("SecretRequiredJwsAlgorithms", resourceCulture);
            }
        }
    }
}
