name: Publish module

on:
  release:
    types:
    - published

jobs:
  publish:
    name: publish
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Download
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ci.yml
        commit: ${{ github.sha }}
        name: PSModule

    - name: Upload nupkg as release asset
      uses: softprops/action-gh-release@v1
      with:
        files: '*.nupkg'

    - name: Publish to the PowerShell Gallery
      shell: pwsh
      run: >-
        dotnet nuget push '*.nupkg'
        --api-key $env:PSGALLERY_API_KEY
        --source 'https://www.powershellgallery.com/api/v2/package'
        --no-symbols
      env:
        PSGALLERY_API_KEY: ${{ secrets.PSGALLERY_API_KEY }}
